### ISSUE TITLE
migration:generate throws an error

### ISSUE THREAD

**Issue by guilherme-gjv** [guilherme-gjv/jovem-plantas#1]
*branch: "routes"

*I'm using Postgres 13;

![image](https://user-images.githubusercontent.com/83377948/168018347-1aa7aa8e-d6c2-45b4-aa92-1f3a86057cc4.png)

*My .env:

![image](https://user-images.githubusercontent.com/83377948/168018533-3c173b23-b610-40bb-8092-d925181ccc2a.png)

*The error:

![image](https://user-images.githubusercontent.com/83377948/168017714-8afd6833-4aba-48bf-94b8-4b04d23f04b3.png)

Error during migration generation:
QueryFailedError: column cnst.consrc does not exist
    at new QueryFailedError (C:\Users\guilherme\Documents\GitHub\nestjs-estudos\jovem-plantas\src\error\QueryFailedError.ts:7:9)  
    at Query.callback (C:\Users\guilherme\Documents\GitHub\nestjs-estudos\jovem-plantas\src\driver\postgres\PostgresQueryRunner.ts:170:26)
    at Query.handleError (C:\Users\guilherme\Documents\GitHub\nestjs-estudos\jovem-plantas\node_modules\pg\lib\query.js:128:19)   
    at Client._handleErrorMessage (C:\Users\guilherme\Documents\GitHub\nestjs-estudos\jovem-plantas\node_modules\pg\lib\client.js:335:17)
    at Connection.emit (node:events:390:28)
    at Connection.emit (node:domain:475:12)
    at C:\Users\guilherme\Documents\GitHub\nestjs-estudos\jovem-plantas\node_modules\pg\lib\connection.js:114:12
    at Parser.parse (C:\Users\guilherme\Documents\GitHub\nestjs-estudos\jovem-plantas\node_modules\pg-protocol\src\parser.ts:104:9)
    at Parser.parse (C:\Users\guilherme\Documents\GitHub\nestjs-estudos\jovem-plantas\node_modules\pg-protocol\src\parser.ts:104:9)
    at Socket.<anonymous> (C:\Users\guilherme\Documents\GitHub\nestjs-estudos\jovem-plantas\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:390:28) {
  length: 196,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: 'Perhaps you meant to reference the column "cnst.conkey" or the column "cnst.conbin".',
  position: '112',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3524',
  routine: 'errorMissingColumn',
  query: `SELECT "ns"."nspname" AS "table_schema", "t"."relname" AS "table_name", "cnst"."conname" AS "constraint_name", "cnst"."consrc" AS "expression", CASE "cnst"."contype" WHEN 'p' THEN 'PRIMARY' WHEN 'u' THEN 'UNIQUE' WHEN 'c' THEN 'CHECK' END AS "constraUNIQUE' WHEN 'c' THEN 'CHECK' END AS "constraint_type", "a"."attname" AS "column_name" FROM "pg_constraint" "cnst" INNER JOIN "pg_class" "t" ON "t"."oid" = "cnst"."conrelid" INNER JOIN "pg_namespace" "ns" ON "ns"."otribute" "a" ON "a"."attrelid" = "cnst"."conrid" = "cnst"."connamespace" INNER JOIN "pg_attribute" "a" ON "a"."attrelid" = "cnst"."conrelid" AND "a"."attnum" = ANY ("cnst"."conkey") WHERE "t"."relkind" = 'r' AND (("ns"."nspname" = 'public' AND "t"."relname" = 
'plant'))`,
  parameters: []
}

**Comment by guilherme-gjv** [comment]
eu estava rodando com "yarn run typeorm migration:generate -n create-plant-migration", e não "yarn run typeorm migration:create -n create-plant-migration" 🤡
